"""add col to account

Revision ID: cd22069b3fc9
Revises: 09a8d1878d9b
Create Date: 2024-11-13 03:11:31.525801

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd22069b3fc9'
down_revision = '09a8d1878d9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month_before_banned', sa.Integer(), server_default=sa.text('12'), nullable=False))
        batch_op.add_column(sa.Column('max_of_apps', sa.Integer(), server_default=sa.text('10'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('max_of_apps')
        batch_op.drop_column('month_before_banned')

    # ### end Alembic commands ###
